service:
  name: rke-graphql

# Add the serverless-webpack plugin
plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: src/handler.graphqlHandler
    events:
    - http:
        path: graphql
        method: post
        cors: true
    - http:
        path: graphql
        method: get
        cors: true
  # graphql:
  #   handler: src/handler.recipegql
  #   events:
  #     - http:
  #         method: post
  #         path: graphql
