service:
  name: rke-graphql

# Add the serverless-webpack plugin
plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

functions:
  graphql:
    handler: src/handler.graphqlHandler
    events:
    - http:
        path: graphql
        method: post
    - http:
        path: graphql
        method: get
  options:
    handler: src/handler.optionsHandler
    events:
    - http:
        path: graphql
        method: options
