service:
  name: rke-graphql

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x

functions:
  graphql:
    handler: src/handler.gqlHandler
    events:
    - http:
        path: graphql
        method: post
  options:
    handler: src/handler.optionsHandler
    events:
    - http:
        path: graphql
        method: options
