service:
  name: rke-graphql

# Add the serverless-webpack plugin
plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

functions:
  recipe:
    handler: src/handler.recipegql
    events:
      - http:
          method: post
          path: recipe
